version: '3'
services:
  hq:
    container_name: hq
    build: .
    image: hq:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT:-1337}:1337
    networks:
      - hq
    depends_on:
      - hqDb

  hqDb:
    container_name: hqDb
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-hq}
      POSTGRES_USER: ${DATABASE_USER:-pgUser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ${DATABASE_DATA_PATH:-./data}:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - hq

networks:
  hq:
    driver: bridge