version: '3'
services:
  viconDb:
    container_name: viconDb
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-vicon}
      POSTGRES_USER: ${DATABASE_USER:-pgUser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ../.dev-data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432